In [1]:
import numpy as np
import matplotlib.pyplot as plt

def NewtonianForce(mass1,mass2, r):
    return (6.67408*10**-11)*mass1*mass2/r/r;

In [2]:
def euler(h,t, x,f):
    return (f(t+h,x+h)-f(t,h)/2./h)

In [3]:
def RK4(h,t,y,f):
    k1= h*f(t,y)
    k2=h*f(t+h/2.,y+h*k1/2.)
    k3=h*f(t+h/2.,y+h*k2/2.)
    k4=h*f(t+h,y+h*k3)
    return t+h,y+h, y+1/6.*(k1+2.*k2+2.*k3+k4)



In [4]:
def polynomial4(t,x,a,b,c,d,e):
    p=[]
    for xi in x:
        pi=a*xi**4+b*xi**3+c*xi**2+d*xi+e
        #print(pi)
        p.append(pi)
    return np.array(p)
    

def polymaker(t,x,a,b,c,d,e):
    def poly(t,x):
        return polynomial4(t,x,a,b,c,d,e)
    return poly
        
        

In [5]:
import numpy as np
t=0.
x=0.01*np.arange(10.)
print(t,x)
polyfn=polymaker(t,x,1.,0.,0.,0.,0.)

0.0 [0.   0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09]


In [6]:
#import matplotlib.pyplot as plt
#plt.plot(t,polyfn(t,x))

In [7]:
y=polyfn(t,x) #this is correct to order of magnitude
print(y)

[0.000e+00 1.000e-08 1.600e-07 8.100e-07 2.560e-06 6.250e-06 1.296e-05
 2.401e-05 4.096e-05 6.561e-05]


In [8]:
from bokeh.plotting import figure, output_notebook, show
# create a new plot with a title and axis labels

output_notebook()
p = figure(title="Polynomial function (x^4)", x_axis_label='x', y_axis_label='y')

# add a line renderer with legend and line thickness
p.line(x, y, legend="Quartic polynomial", line_width=2)

# show the results
show(p)

Loading BokehJS ...

In [9]:
rk4polyout=RK4(.01,t,x,polyfn)
print(y+x)

[0.         0.01000001 0.02000016 0.03000081 0.04000256 0.05000625
 0.06001296 0.07002401 0.08004096 0.09006561]


In [10]:
print(rk4polyout) 
#There are multiple items in the y output, which is confusing. trace this over time and plot an evolution and compare to exact solution, which I have analytically written down. steve points out truncation error
print((rk4polyout[2]-y-x)/y)
#order4 polynomial error (comparable in size to polyfn itself, relative error with it is one)

(0.01, array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ]), array([0.        , 0.01      , 0.02      , 0.03000001, 0.04000003,
       0.05000006, 0.06000013, 0.07000024, 0.08000041, 0.09000066]))
[  nan -0.99 -0.99 -0.99 -0.99 -0.99 -0.99 -0.99 -0.99 -0.99]


/Users/sdorsher/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until


In [11]:
def invpolyint(t,x):
    p=[]
    for ti in t:
        xi=-3*t**(-1./3.)
        p.append(xi)
    return np.array(p)
    



In [12]:
#print(invpolyint(t,x)) #need an entire run to invert this because you need a history of a timeseries accumulated

In [13]:
def analyticalpolyint(t,x):
    p=[]
    for xi in x:
        ti = -1./3.*xi**(-3.)
        p.append(ti)
    return np.array(p)

In [14]:
print(x)

[0.   0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09]


In [15]:
#print(analyticalpolyint(t,x))

In [16]:
def invertIMF(luminosity,lsun,masssun):
    M=[]
    for L in luminosity: 
        if (L<(.43)**4)*lsun:
            x=((L/lsun/0.23)**(1./2.3))*masssun
            #print(x,1)
            M.append(x)
        elif (L<16*lsun):
            x=(((L/lsun)**(0.25))*masssun)
            #print(L,lsun,masssun,x,2)
            M.append(x)
        elif (L<(((20**(3.5))*1.4)*masssun)):
            x=(((L/lsun/1.4)**(1./3.5))*masssun)
            #print(x,3)
            M.append(x)
        else:
            x=((L/lsun/32000.)*masssun)
            #print(x,4)
            M.append(x)
    return np.array(M)
    

In [55]:
def InitialData():
    random.seed(a=9001)
    
    #initially use an in plane orbit with random starting locations relative to the x axis
    phi=np.random.uniform(0,1,2)
    orbitangle=np.zeros(2)
    #orbitalradius=np.random.uniform(.1,50,2)
    orbitalradius=np.ones(2)
    #start with circular orbits
    #eccentricity=np.random.uniform(0.,.1,2)
    eccentricity=np.zeros(2)
    #magnitude=np.random.uniform(-20,-30,2) #absolute not apparent maginutde
    #magsun=-26.832
    masssun=1.989*10**30
    lsun=3.828*10**26
    massearth=5.9722*10**24
    #luminosity=lsun*10**(0.4*(magnitude-magsun))
    #masses= invertIMF(luminosity,lsun,masssun) #Initial mass function for Main Sequence
    #masses=np.random.uniform(.7,5.) #replace with IMF
    masses=np.array([masssun,massearth])

    return phi,orbitangle,orbitalradius,eccentricity, masses



In [56]:
import random
initdat=InitialData()

In [57]:
print(initdat)

(array([0.33216121, 0.15390364]), array([0., 0.]), array([1., 1.]), array([0., 0.]), array([1.9890e+30, 5.9722e+24]))


In [100]:
def getxyuv(initdat):
    phi,orbitangle,orbitalradius,eccentricity, masses=initdat
    #print(orbitalradius, phi, np.cos(phi), np.sin(phi))
    metersperAU=149597870700
    Gconstant=6.408*10**-11
    x0=orbitalradius*np.cos(phi)*metersperAU
    y0=orbitalradius*np.sin(phi)*metersperAU
    z0=np.zeros(2)
    

    
    #start at perihelion for both (eliptical, doesn't generalize to three body)
    #actually start with circular orbit
    ux0=np.zeros(2)*149597870700
    #centrepital force balances gravitational force
    reducedmass=np.zeros(2)
    print(masses)
    for i in np.arange(2):
        j=(i+1)%2 #reverse masses
        reducedmass[i]=masses[i]*mass[j]/np.sum(masses)
    print(reducedmass)
    rphys=orbitalradius*metersperAU*reducedmass/np.sum(masses)
    print(rphys)
    F=(Gconstant*reducedmass**2/rphys**2)
    print(F)
    #centF=reducedmass*v**2/rphys
    #centF=accel
    v=np.sqrt(Gconstant*reducedmass/rphys)
    print(v)
    uy0=v #initial data in y only
    #evolve in plane only
    #there is a units problem that needs to be fixed
    #velocity initial conditions are not trivial. 
    uz0=np.zeros(2)
    
    #circular orbit
    ax0=np.zeros(2)
    ay0=np.zeros(2)
    az0=np.zeros(2)
    
    
    return reducedmass,x0,y0,z0, ux0, uy0,uz0, ax0, ay0,az0

In [101]:
xyuva=getxyuv(initdat)
print(xyuva)#In SI units
print(xyuva[1][0])
print(xyuva[0][0]/xyuva[0][1])

[1.9890e+30 5.9722e+24]
[5.97218207e+24 5.97218207e+24]
[449182.02019948 449182.02019948]
[1.13277552e+28 1.13277552e+28]
[29188.82340899 29188.82340899]
(array([5.97218207e+24, 5.97218207e+24]), array([1.41420823e+11, 1.47829653e+11]), array([4.87819006e+10, 2.29328737e+10]), array([0., 0.]), array([0., 0.]), array([29188.82340899, 29188.82340899]), array([0., 0.]), array([0., 0.]), array([0., 0.]), array([0., 0.]))
141420822706.88956
1.0


In [155]:
def timestep(step,t,dt,reducedmass,xi,yi,zi, vxi, vyi, vzi, axi, ayi, azi):
    xii=np.zeros(np.size(xi))
    vxii=np.zeros(np.size(vx))
    yii=np.zeros(np.size(yi))
    vyii=np.zeros(np.size(vy))
    zii=np.zeros(np.size(vzi))
    vzii=np.zeros(np.size(vzi))
    rii=np.zeros(np.size(xi))
    axii=np.zeros(np.size(axi))
    ayii=np.zeros(np.size(ayi))
    azii=np.zeros(np.size(azi))
    
    for m in np.arange(len(x)):
        #m represents choices of mass
        i=step
        
        xii[m] = xi[m] + dt*vxi[m]
        #print(xii)
        vxii[m] = vxi[m] + dt*axi[m]
        #print(vxii)
        yii[m]= yi[m] + dt*vyi[m]
        vyii[m] = vyi[m] + dt*ayi[m]
        zii[m]= zi[m] + dt*vzi[m]
        vzii[m] = vzi[m] + dt*azi[m]
        rii[m]=np.sqrt(xi[m]**2+yi[m]**2+zi[m]**2)
    
    
    Gconstant=6.408*10**-11
    for k in np.arange(len(rii)):
        for j in np.arange(len(rii)):
            if j!=k:
                axii[j]+=Gconstant*reducedmass[k]*(x[j]  - x[k])/np.abs((xii[j] - xii[k])**2+(yii[j]-yii[k])**2+(zii[j]-zii[k])**2)**(3./2.)
                ayii[j]+=Gconstant*reducedmass[k]*(y[j]  - y[k])/np.abs((xii[j] - xii[k])**2+(yii[j]-yii[k])**2+(zii[j]-zii[k])**2)**(3./2.)
                azii[j]+=Gconstant*reducedmass[k]*(z[j]  - z[k])/np.abs((xii[j] - xii[k])**2+(yii[j]-yii[k])**2+(zii[j]-zii[k])**2)**(3./2.)
    #print(xii)
    return reducedmass, xii,yii,zii,vxii,vyii,vzii,axii,ayii,azii
                    

In [156]:
dt=0.01*31556926 #seconds per year
numsteps=100
mass,x,y,z,vx,vy,vz,ax,ay,az=xyuva
for i in np.arange(1,numsteps):
    t=0.+i*numsteps*dt
    mass, x,y,z,vx,vy,vz,ax,ay,az=timestep(i,t,dt,mass,x,y,z,vx,vy,vz,ax,ay,az)
    #print(x,y,vx,vy,ax,ay)
    print(ay) #forces should be equal and opposite, but in reduced mass framework accelerations are also equal and opposite
    #accelerations should evolve from y to x with time in a sinusoidal manner even in reduced mass framework
    print(ax)
#mass, x,y,z,vx,vy,vz,ax,ay,az=timestep(2,0,dt,mass,x,y,z,vx,vy,vz,ax,ay,az)
#print(x,y,vx,vy,ax,ay) 
#mass, x,y,z,vx,vy,vz,ax,ay,az=timestep(3,0,dt,mass,x,y,z,vx,vy,vz,ax,ay,az)
#print(x,y,vx,vy,ax,ay) 
#mass, x,y,z,vx,vy,vz,ax,ay,az=timestep(4,0,dt,mass,x,y,z,vx,vy,vz,ax,ay,az)
#print(x,y,vx,vy,ax,ay) 

[ 5.23727101e-07 -5.23727101e-07]
[ 5.23727101e-07 -5.23727101e-07]
[ 5.23720761e-07 -5.23720761e-07]
[ 5.23710194e-07 -5.23710194e-07]
[ 5.23695401e-07 -5.23695401e-07]
[ 5.23676383e-07 -5.23676383e-07]
[ 5.2365314e-07 -5.2365314e-07]
[ 5.23625673e-07 -5.23625673e-07]
[ 5.23593984e-07 -5.23593984e-07]
[ 5.23558074e-07 -5.23558074e-07]
[ 5.23517945e-07 -5.23517945e-07]
[ 5.23473598e-07 -5.23473598e-07]
[ 5.23425035e-07 -5.23425035e-07]
[ 5.23372259e-07 -5.23372259e-07]
[ 5.23315271e-07 -5.23315271e-07]
[ 5.23254075e-07 -5.23254075e-07]
[ 5.23188672e-07 -5.23188672e-07]
[ 5.23119066e-07 -5.23119066e-07]
[ 5.2304526e-07 -5.2304526e-07]
[ 5.22967258e-07 -5.22967258e-07]
[ 5.22885061e-07 -5.22885061e-07]
[ 5.22798675e-07 -5.22798675e-07]
[ 5.22708103e-07 -5.22708103e-07]
[ 5.22613349e-07 -5.22613349e-07]
[ 5.22514417e-07 -5.22514417e-07]
[ 5.22411312e-07 -5.22411312e-07]
[ 5.22304037e-07 -5.22304037e-07]
[ 5.22192598e-07 -5.22192598e-07]
[ 5.22077e-07 -5.22077e-07]
[ 5.21957248e-07 -5.2195