In [1]:
import math
import numpy as np

In [2]:
import ellipsefns
#getfocus, getsemiminor, theoreticalx, theoreticaly

In [3]:
import initdat

In [4]:

rad0=50
ecc0=0.9
theta0=math.pi/6. #math.pi/6.
mass0=1.0
initdateqellipse=initdat.InitialDataEqualMassConic(rad0,ecc0,theta0,mass0)
print(initdateqellipse)

angle 0.5235987755982988
0.9
(array([3.66519143, 0.52359878]), 0.5235987755982988, 50, 0.9, array([1., 1.]))


VERIFIED FOR THETA=-45,45,135,180,90,30,-30. VERIFIED FOR ECC =0.001, 0.1,0.5, 0.7, 0.9, 0.95 VERIFIED FOR RAD0=50,75 100 

In [5]:
import getxyuvtwoellipse

In [6]:
xyuvaeqellipse=getxyuvtwoellipse.getxyuveqtwoellipses(initdateqellipse)
print(xyuvaeqellipse)
masses,xvec,avec=xyuvaeqellipse

initdat 50 [3.66519143 0.52359878] 0.9 [-0.8660254  0.8660254] [-0.5  0.5]
coordsep 50
[-43.30127019  43.30127019]
[-25.  25.]
(array([1., 1.]), array([[-8.22724134e+01, -4.75000000e+01,  0.00000000e+00,
         8.11107106e-03, -1.40487872e-02,  0.00000000e+00],
       [ 8.22724134e+01,  4.75000000e+01,  0.00000000e+00,
        -8.11107106e-03,  1.40487872e-02,  0.00000000e+00]]), array([[ 2.39896234e-05,  1.38504155e-05,  0.00000000e+00],
       [-2.39896234e-05, -1.38504155e-05,  0.00000000e+00]]))


In [7]:
import RK4implicit

In [8]:
import OrbitDiffEq

In [9]:
masses, xvec,avec=xyuvaeqellipse
ODEeq= OrbitDiffEq.OrbitDiffEq(masses,xvec,avec,0.0)
ODEeq.print2D()
ODEeq.print2D()

[1. 1.] [[-8.22724134e+01 -4.75000000e+01  0.00000000e+00  8.11107106e-03
  -1.40487872e-02  0.00000000e+00]
 [ 8.22724134e+01  4.75000000e+01  0.00000000e+00 -8.11107106e-03
   1.40487872e-02  0.00000000e+00]] 0.0
[1. 1.] [[-8.22724134e+01 -4.75000000e+01  0.00000000e+00  8.11107106e-03
  -1.40487872e-02  0.00000000e+00]
 [ 8.22724134e+01  4.75000000e+01  0.00000000e+00 -8.11107106e-03
   1.40487872e-02  0.00000000e+00]] 0.0


In [10]:
print(xyuvaeqellipse)

(array([1., 1.]), array([[-8.22724134e+01, -4.75000000e+01,  0.00000000e+00,
         8.11107106e-03, -1.40487872e-02,  0.00000000e+00],
       [ 8.22724134e+01,  4.75000000e+01,  0.00000000e+00,
        -8.11107106e-03,  1.40487872e-02,  0.00000000e+00]]), array([[ 2.39896234e-05,  1.38504155e-05,  0.00000000e+00],
       [-2.39896234e-05, -1.38504155e-05,  0.00000000e+00]]))


In [11]:
import timestep

In [12]:
numsteps=6000
dt=1
outputevery=20
nptimes, npstar1x, npstar2x, npstar1a, npstar2a= timestep.timestep(numsteps,dt,xyuvaeqellipse,outputevery)

In [13]:
import ellipsefns
from bokeh.io import output_notebook, show
from bokeh.plotting import figure
output_notebook()
import numpy as np
# create a new plot with default tools, using figure
p = figure(title="Elliptical orbit, RK4, a="+str(rad0)+", e="+ str(ecc0)+", theta="+str(round(180*theta0/math.pi))+ " degrees", plot_width=400, plot_height=400, x_range=(-200,200), y_range=(-200,200))
t = np.linspace(0, 2*math.pi, 100)
xax=-200+np.arange(0,400)
#theta0=math.pi/6.
# add a circle renderer with x and y coordinates, size, color, and alpha
p.line(ellipsefns.getxtheory(theta0,ecc0,rad0,t,1),ellipsefns.getytheory(theta0,ecc0,rad0,t,1), line_color="cyan", legend="Ideal Ellipse 1")
p.line(ellipsefns.getxtheory(theta0,ecc0,rad0,t,-1),ellipsefns.getytheory(theta0,ecc0,rad0,t,-1),line_color="black", legend="Ideal Ellipse 2")
p.line(npstar1x[:,0],npstar1x[:,1], line_color="purple", legend="Star 1")
p.line(npstar2x[:,0],npstar2x[:,1], line_color="blue", legend="Star 2")
p.line(xax, np.tan(theta0)*xax,line_color="green")
p.legend.location = "bottom_left"
p.legend.click_policy="hide"

show(p) # show the

Loading BokehJS ...

%%html
<a href="https://github.com/sdorsher/ManyBodyProblem/blob/master/EllipseSymmetry.png">Elliptical orbits at thirty degrees with symmetry line</a>
It is clear that the elliptical orbits have focuses, perhelions, and aphelions on the axis of symmetry from this plot. It is also clear that the orbits are symmetric with respect to eachother. 

In [14]:
import Lstability

In [15]:
deltaL, Lavg=Lstability.Lstability(npstar1x,npstar2x,mass0)
deltaL, Lavg

(4.278550941562962e-09, -1.0274023310582483)

In [ ]:
assert deltaL<1e-5, "Angular momentum is not constant, relative error greater than 1e-5"

Orbit conserves angular momentum to a tolerance of one part in 10^5

In [17]:
import Estability

In [18]:
deltaE, Eavg = Estability.Estability(npstar1x, npstar2x, mass0)
deltaE, Eavg

(1.0589843108096096e-07, -0.005000000634119679)

In [19]:
assert deltaE < 1e-5, "Energy is not constant, relative error greater than 1e-5"

In [20]:
npstar1x

array([[-8.21053971e+01, -4.77782002e+01,  0.00000000e+00,
         8.59040633e-03, -1.37709504e-02,  0.00000000e+00],
       [-8.19288028e+01, -4.80508267e+01,  0.00000000e+00,
         9.06889027e-03, -1.34914192e-02,  0.00000000e+00],
       [-8.17426465e+01, -4.83178452e+01,  0.00000000e+00,
         9.54661696e-03, -1.32101368e-02,  0.00000000e+00],
       ...,
       [-4.18255129e+01, -4.81105927e+01,  0.00000000e+00,
         4.94258423e-02,  2.00070009e-02,  0.00000000e+00],
       [-4.08288665e+01, -4.77010530e+01,  0.00000000e+00,
         5.02417135e-02,  2.09528017e-02,  0.00000000e+00],
       [-3.98157244e+01, -4.72722387e+01,  0.00000000e+00,
         5.10755855e-02,  2.19348960e-02,  0.00000000e+00]])

In [22]:
import orbitsSymmetricTest

In [23]:
allopposite=orbitsSymmetricTest.isSymmetric(npstar1x,npstar2x,npstar1a,npstar2a)

In [24]:
assert allopposite, "Orbit is not symmetric in r, v, and a > tol 10^-12"

Orbit is symmetric with respect to r,v,and a up to a tolerance of 10^-12

Test how well the orbital plane conforms to a line and how well the perihelion and aphelion are on that line by binning in x and averaging over y. This also allows idenfication of perihelion and aphelion for the purpose of determining if the eccentricity and semimajor axis are correct. Can use a histogram to do this if the bins are big enough, then divide by the number of elements in the bin. 

In [27]:
npstar1x[0,0]-npstar1x[1,0]

-0.17659430629139194

In [34]:
npstar1x[100,0]-npstar1x[101,0]

-1.6443201525621554

In [62]:
absdistx=np.abs(npstar1x[:,0]-npstar1x[0,0])

In [63]:
absdistx

array([0.00000000e+00, 1.76594306e-01, 3.62750563e-01, 5.58454560e-01,
       7.63693954e-01, 9.78458259e-01, 1.20273884e+00, 1.43652889e+00,
       1.67982348e+00, 1.93261949e+00, 2.19491566e+00, 2.46671257e+00,
       2.74801265e+00, 3.03882020e+00, 3.33914136e+00, 3.64898419e+00,
       3.96835861e+00, 4.29727645e+00, 4.63575148e+00, 4.98379941e+00,
       5.34143791e+00, 5.70868665e+00, 6.08556731e+00, 6.47210362e+00,
       6.86832141e+00, 7.27424859e+00, 7.68991524e+00, 8.11535364e+00,
       8.55059830e+00, 8.99568600e+00, 9.45065588e+00, 9.91554943e+00,
       1.03904106e+01, 1.08752859e+01, 1.13702243e+01, 1.18752775e+01,
       1.23904998e+01, 1.29159484e+01, 1.34516834e+01, 1.39977678e+01,
       1.45542677e+01, 1.51212521e+01, 1.56987938e+01, 1.62869684e+01,
       1.68858554e+01, 1.74955378e+01, 1.81161023e+01, 1.87476397e+01,
       1.93902447e+01, 2.00440162e+01, 2.07090577e+01, 2.13854772e+01,
       2.20733875e+01, 2.27729065e+01, 2.34841572e+01, 2.42072683e+01,
      

In [68]:
indexminx=np.argmin(absdistx[1:])

In [69]:
indexminx

221

In [70]:
npstar1x[indexminx,0]

-82.29566339611775

In [71]:
npstar1x[0,0]

-82.10539708801772

Reverse count between 0 and index 221, instead, in pairs, rather than histogramming. Maybe interpolation is also necessary to get true symmetry

Minimize line along predicted path, maximize line along predicted path, to find perihelion and aphelion. Match ecentricities and semimajor axis that way.

In [72]:
b=np.tan(theta0)

looking for y/x = b. two points. 

In [74]:
npstar1x[0,1]/npstar1x[0,0]/b

1.0079029283482996

In [83]:
mostb1=np.abs(1-npstar1x[:,1]/npstar1x[:,0]/b)

In [91]:
mostb1

array([7.90292835e-03, 1.58390016e-02, 2.38102929e-02, 3.18189112e-02,
       3.98670047e-02, 4.79567640e-02, 5.60904246e-02, 6.42702712e-02,
       7.24986402e-02, 8.07779240e-02, 8.91105744e-02, 9.74991068e-02,
       1.05946104e-01, 1.14454221e-01, 1.23026190e-01, 1.31664822e-01,
       1.40373019e-01, 1.49153770e-01, 1.58010166e-01, 1.66945399e-01,
       1.75962772e-01, 1.85065704e-01, 1.94257740e-01, 2.03542556e-01,
       2.12923968e-01, 2.22405941e-01, 2.31992600e-01, 2.41688236e-01,
       2.51497321e-01, 2.61424517e-01, 2.71474691e-01, 2.81652924e-01,
       2.91964531e-01, 3.02415070e-01, 3.13010367e-01, 3.23756524e-01,
       3.34659947e-01, 3.45727364e-01, 3.56965847e-01, 3.68382838e-01,
       3.79986175e-01, 3.91784123e-01, 4.03785405e-01, 4.15999238e-01,
       4.28435369e-01, 4.41104120e-01, 4.54016432e-01, 4.67183916e-01,
       4.80618907e-01, 4.94334529e-01, 5.08344758e-01, 5.22664500e-01,
       5.37309674e-01, 5.52297299e-01, 5.67645602e-01, 5.83374130e-01,
      

In [84]:
mostb2=np.abs(1-b/npstar1x[:,1]*npstar1x[:,0])

In [92]:
mostb2

array([7.84096179e-03, 1.55920393e-02, 2.32565477e-02, 3.08376895e-02,
       3.83385611e-02, 4.57621589e-02, 5.31113845e-02, 6.03890505e-02,
       6.75978854e-02, 7.47405385e-02, 8.18195843e-02, 8.88375272e-02,
       9.57968057e-02, 1.02699796e-01, 1.09548816e-01, 1.16346130e-01,
       1.23093949e-01, 1.29794440e-01, 1.36449723e-01, 1.43061877e-01,
       1.49632944e-01, 1.56164931e-01, 1.62659812e-01, 1.69119534e-01,
       1.75546014e-01, 1.81941149e-01, 1.88306813e-01, 1.94644862e-01,
       2.00957139e-01, 2.07245470e-01, 2.13511675e-01, 2.19757564e-01,
       2.25984943e-01, 2.32195617e-01, 2.38391390e-01, 2.44574072e-01,
       2.50745479e-01, 2.56907434e-01, 2.63061777e-01, 2.69210361e-01,
       2.75355059e-01, 2.81497767e-01, 2.87640407e-01, 2.93784931e-01,
       2.99933324e-01, 3.06087613e-01, 3.12249863e-01, 3.18422190e-01,
       3.24606761e-01, 3.30805800e-01, 3.37021596e-01, 3.43256509e-01,
       3.49512972e-01, 3.55793506e-01, 3.62100720e-01, 3.68437326e-01,
      

In [85]:
mostb=[]
for b1,b2 in zip(mostb1,mostb2): 
    mostb.append(min(b1,b2))


In [86]:
np.argmin(mostb)

221

In [87]:
np.argmin(mostb[0:220])

0

In [88]:
np.argmin(mostb[1:200])

0

In [89]:
npstar1x[221,0]

-82.29566339611775

In [90]:
np.argmin(mostb[20:190])

0

In [93]:
mostb

[0.007840961789098766,
 0.015592039307009364,
 0.023256547660376103,
 0.03083768945423848,
 0.03833856112165901,
 0.04576215890671953,
 0.05311138452691988,
 0.06038905053907828,
 0.06759788543106782,
 0.07474053846016526,
 0.08181958425732794,
 0.08883752721542193,
 0.09579680567825455,
 0.10269979594618639,
 0.10954881611315392,
 0.11634612974905989,
 0.12309394944072638,
 0.1297944402039054,
 0.13644972277824252,
 0.1430618768165357,
 0.14963294397917626,
 0.1561649309442471,
 0.16265981234341476,
 0.1691195336334762,
 0.17554601391319247,
 0.18194114869489575,
 0.1883068126402393,
 0.19464486226942102,
 0.20095713865323517,
 0.20724547009736782,
 0.2135116748285063,
 0.21975756369202915,
 0.22598494287132176,
 0.2321956166391108,
 0.23839139015164024,
 0.2445740722970282,
 0.2507454786097437,
 0.2569074342638604,
 0.26306177715856716,
 0.269210361110357,
 0.27535505916740843,
 0.2814977670629152,
 0.2876404068255377,
 0.2937849305667626,
 0.2999333244667973,
 0.3060876129827118,
 0

Looking for the index that is less than both its neighbors (this is actually in a fairly high value neighborhood because it is changing rapidly at apastron) There are only two such indicies

In [98]:
def localMinimumIndex(values):
    mins=[]
    secondtolastval=values[0]
    lastval=values[1]
    for i in np.arange(2,len(values)):
        thisval=values[i]
        if thisval>lastval and lastval<secondtolastval:
            mins.append(i-1)
        secondtolastval=lastval
        lastval=thisval
    return mins

In [99]:
mins=localMinimumIndex(mostb)

In [100]:
mins

[110, 221]

In [101]:
mostb[110]

0.1954525767952412

In [102]:
mostb[221]

0.0011357800189867318

Tolerance on aphelion is 20%. Tolerance on perihelion is 1%. 

In [103]:
coordap=[npstar1x[110,0],npstar1x[110,1]]

In [104]:
coordper=[npstar1x[221,0],npstar1x[221,1]]

In [105]:
coordap

[4.543132868313713, 2.110310983087769]

In [106]:
coordper

[-82.29566339611775, -47.45945861793911]

In [108]:
np.sqrt(np.sum(np.array(coordper)**2))

94.99987592683998

In [112]:
np.argmax(npstar1x[:,1])

114

In [113]:
np.argmax(npstar1x[:,0])

109