In [1]:
import math
import numpy as np

In [2]:
import ellipsefns
#getfocus, getsemiminor, theoreticalx, theoreticaly

In [3]:
import initdat

In [4]:

rad0=50
ecc0=0.5
theta0= 0. #math.pi/6. #math.pi/6.
mass0=1.0
initdateqellipse=initdat.InitialDataEqualMassConic(rad0,ecc0,theta0,mass0)
print(initdateqellipse)

angle 0.0
0.5
(array([3.14159265, 0.        ]), 0.0, 50, 0.5, array([1., 1.]))


In [5]:
import getxyuvtwoellipse_apper

In [6]:
useperihelion=True

In [7]:
xyuvaeqellipse=getxyuvtwoellipse_apper.getxyuveqtwoellipses(initdateqellipse,useperihelion)
print(xyuvaeqellipse)
masses,xvec,avec=xyuvaeqellipse

initdat 50 [3.14159265 0.        ] 0.5 [-1.  1.] [1.2246468e-16 0.0000000e+00]
coordsep 50
pi
zero
[-50.  50.]
[0. 0.]
(array([1., 1.]), array([[-25.        ,   0.        ,   0.        ,  -0.        ,
         -0.12247449,   0.        ],
       [ 25.        ,   0.        ,   0.        ,  -0.        ,
          0.12247449,   0.        ]]), array([[ 0.0004, -0.    ,  0.    ],
       [-0.0004, -0.    ,  0.    ]]))


In [8]:
import RK4implicit

In [9]:
def RK4implicit(h,t,xvec,f): #not a finite difference so no step in y
    k1= h*f(t,xvec)
    k2=h*f(t+h/2, xvec+k1/2)
    k3=h*f(t+h/2,xvec+k2/2)
    k4=h*f(t+h,xvec+k3)
    return t+h, xvec+1/6.*(k1+2.*k2+2.*k3+k4)

In [10]:
import OrbitDiffEqAdaptive

In [11]:
masses, xvec,avec=xyuvaeqellipse
delta=0.001
ODEeq= OrbitDiffEqAdaptive.OrbitDiffEqAdaptive(masses,xvec,avec,0.0, delta)
ODEeq.print2D()
ODEeq.print2D()

[1. 1.] [[-25.           0.           0.          -0.          -0.12247449
    0.        ]
 [ 25.           0.           0.          -0.           0.12247449
    0.        ]] 0.0
[1. 1.] [[-25.           0.           0.          -0.          -0.12247449
    0.        ]
 [ 25.           0.           0.          -0.           0.12247449
    0.        ]] 0.0


In [12]:
print(xyuvaeqellipse)

(array([1., 1.]), array([[-25.        ,   0.        ,   0.        ,  -0.        ,
         -0.12247449,   0.        ],
       [ 25.        ,   0.        ,   0.        ,  -0.        ,
          0.12247449,   0.        ]]), array([[ 0.0004, -0.    ,  0.    ],
       [-0.0004, -0.    ,  0.    ]]))


In [13]:
import timestepAdaptive

In [25]:
numsteps=10000

#numsteps=6000*10
dt=.01
dtmax=.1
outputevery=1
nptimes, npstar1x, npstar2x, npstar1a, npstar2a= timestepAdaptive.timestepAdaptive(numsteps,dt,dtmax,xyuvaeqellipse,outputevery,delta)

0.01
[-5.99999979e-08  1.22474487e-03  0.00000000e+00]
[3.59999974e-15 1.49999999e-06 0.00000000e+00]
1.4999999979999992e-06
0.001224744870575092
True 0.007035077828630974 0.01 0.0 0.24494897444161717
0.007035077828630974
[-2.96953928e-08  8.61617548e-04  0.00000000e+00]
[8.81816354e-16 7.42384799e-07 0.00000000e+00]
7.423848003335286e-07
0.0008616175487613565
True 0.004949232005072887 0.007035077828630974 0.0 0.24494897435913845
0.004949232005072887
[-1.46969406e-08  6.06154651e-04  0.00000000e+00]
[2.16000062e-16 3.67423461e-07 0.00000000e+00]
3.67423461480567e-07
0.0006061546514550284
True 0.003481823234325749 0.004949232005072887 0.0 0.2449489743183178
0.003481823234325749
[-7.27385796e-09  4.26434515e-04  0.00000000e+00]
[5.29090096e-17 1.81846395e-07 0.00000000e+00]
1.8184639549696546e-07
0.000426434514898789
True 0.0024494897435429707 0.003481823234325749 0.0 0.24494897429811474
0.0024494897435429707
[-3.6000003e-09  3.0000000e-04  0.0000000e+00]
[1.29600021e-17 9.00000000e-08 0

True 2.250664633747795e-19 3.1992036036378648e-19 0.0 0.24494897427831785
2.250664633747795e-19
[0.00000000e+00 2.75648997e-20 0.00000000e+00]
[0.00000000e+00 7.59823694e-40 0.00000000e+00]
7.598236940404643e-40
2.756489967405041e-20
True 1.5833600861924031e-19 2.250664633747795e-19 0.0 0.24494897427831785
1.5833600861924031e-19
[0.00000000e+00 1.93921215e-20 0.00000000e+00]
[0.00000000e+00 3.76054374e-40 0.00000000e+00]
3.760543743820821e-40
1.93921214513029e-20
True 1.1139061435254895e-19 1.5833600861924031e-19 0.0 0.24494897427831785
1.1139061435254895e-19
[0.00000000e+00 1.36425084e-20 0.00000000e+00]
[0.00000000e+00 1.86118034e-40 0.00000000e+00]
1.8611803448757425e-40
1.3642508364944266e-20
True 7.836416412185934e-20 1.1139061435254895e-19 0.0 0.24494897427831783
7.836416412185934e-20
[0.00000000e+00 9.59761081e-21 0.00000000e+00]
[0.00000000e+00 9.21141333e-41 0.00000000e+00]
9.211413327776558e-41
9.597610810913599e-21
True 5.512979934810085e-20 7.836416412185934e-20 0.0 0.24494

True 3.5636125473051736e-36 5.0654912919315744e-36 0.0 0.24494897427831788
3.5636125473051736e-36
[0.00000000e+00 4.36451619e-37 0.00000000e+00]
[0.00000000e+00 1.90490016e-73 0.00000000e+00]
1.904900158096629e-73
4.3645161909387266e-37
True 2.5070291617199392e-36 3.5636125473051736e-36 0.0 0.24494897427831788
2.5070291617199392e-36
[0.00000000e+00 3.07047111e-37 0.00000000e+00]
[0.00000000e+00 9.42779283e-74 0.00000000e+00]
9.427792826571272e-74
3.0704711082456504e-37
True 1.7637145268407716e-36 2.5070291617199392e-36 0.0 0.2449489742783178
1.7637145268407716e-36
[0.00000000e+00 2.16010032e-37 0.00000000e+00]
[0.0000000e+00 4.6660334e-74 0.0000000e+00]
4.66603339828375e-74
2.160100321347078e-37
True 1.2407868961743904e-36 1.7637145268407716e-36 0.0 0.24494897427831783
1.2407868961743904e-36
[0.00000000e+00 1.51964739e-37 0.00000000e+00]
[0.00000000e+00 2.30932818e-74 0.00000000e+00]
2.309328182577115e-74
1.5196473875794723e-37
True 8.729032381877458e-37 1.2407868961743904e-36 0.0 0.24

2.792595184315894e-53
[0.00000000e+00 3.42021663e-54 0.00000000e+00]
[0.00000000e+000 1.16978818e-107 0.00000000e+000]
1.1697881795196482e-107
3.4202166298637404e-54
True 1.964612446224802e-53 2.792595184315894e-53 0.0 0.24494897427831783
1.964612446224802e-53
[0.00000000e+00 2.40614902e-54 0.00000000e+00]
[0.0000000e+000 5.7895531e-108 0.0000000e+000]
5.789553095792101e-108
2.4061490177859103e-54
True 1.3821201459985034e-53 1.964612446224802e-53 0.0 0.24494897427831783
1.3821201459985034e-53
[0.00000000e+00 1.69274456e-54 0.00000000e+00]
[0.00000000e+000 2.86538415e-108 0.00000000e+000]
2.865384146962386e-108
1.6927445604586613e-54
True 9.723322793997723e-54 1.3821201459985034e-53 0.0 0.24494897427831783
9.723322793997723e-54
[0.00000000e+00 1.19085897e-54 0.00000000e+00]
[0.00000000e+000 1.41814509e-108 0.00000000e+000]
1.4181450923441349e-108
1.1908589724833646e-54
True 6.840433259727483e-54 9.723322793997723e-54 0.0 0.24494897427831783
6.840433259727483e-54
[0.00000000e+00 8.377785

True 6.28519521564018e-70 8.93408057421706e-70 0.0 0.24494897427831783
6.28519521564018e-70
[0.00000000e+00 7.69776061e-71 0.00000000e+00]
[0.00000000e+000 5.92555183e-141 0.00000000e+000]
5.925551834805929e-141
7.697760606050262e-71
True 4.421683750279823e-70 6.28519521564018e-70 0.0 0.24494897427831785
4.421683750279823e-70
[0.0000000e+00 5.4154345e-71 0.0000000e+00]
[0.00000000e+000 2.93269308e-141 0.00000000e+000]
2.932693078123296e-141
5.415434496070741e-71
True 3.110688931162696e-70 4.421683750279823e-70 0.0 0.2449489742783178
3.110688931162696e-70
[0.00000000e+00 3.80980031e-71 0.00000000e+00]
[0.00000000e+000 1.45145784e-141 0.00000000e+000]
1.451457843968717e-141
3.809800314936095e-71
True 2.188393872774314e-70 3.110688931162696e-70 0.0 0.2449489742783178
2.188393872774314e-70
[0.00000000e+00 2.68022417e-71 0.00000000e+00]
[0.00000000e+000 7.18360161e-142 0.00000000e+000]
7.183601613594237e-142
2.680224172265118e-71
True 1.539552121210053e-70 2.188393872774314e-70 0.0 0.244948

[0.00000000e+00 6.03228575e-88 0.00000000e+00]
[0.00000000e+000 3.63884714e-175 0.00000000e+000]
3.638847140635965e-175
6.032285753042511e-88
True 3.46501550987547e-87 4.925340692538244e-87 0.0 0.24494897427831785
3.46501550987547e-87
[0.00000000e+00 4.24375998e-88 0.00000000e+00]
[0.00000000e+000 1.80094987e-175 0.00000000e+000]
1.8009498725516335e-175
4.243759975012293e-88
True 2.4376653785324595e-87 3.46501550987547e-87 0.0 0.24494897427831785
2.4376653785324595e-87
[0.00000000e+00 2.98551817e-88 0.00000000e+00]
[0.00000000e+000 8.91331875e-176 0.00000000e+000]
8.913318746543698e-176
2.9855181705264663e-88
True 1.714916565527684e-87 2.4376653785324595e-87 0.0 0.2449489742783178
1.714916565527684e-87
[0.00000000e+00 2.10033527e-88 0.00000000e+00]
[0.00000000e+000 4.41140824e-176 0.00000000e+000]
4.411408240081897e-176
2.100335268494508e-88
True 1.2064571506085024e-87 1.714916565527684e-87 0.0 0.24494897427831788
1.2064571506085024e-87
[0.00000000e+00 1.47760221e-88 0.00000000e+00]
[0

6.719400157598057e-105
True 3.8597020625877615e-104 5.4863672545640376e-104 0.0 0.24494897427831783
3.8597020625877615e-104
[0.00000000e+000 4.72715031e-105 0.00000000e+000]
[0.000000e+000 2.234595e-209 0.000000e+000]
2.2345950017916318e-209
4.727150306253898e-105
True 2.7153304401106852e-104 3.8597020625877615e-104 0.0 0.24494897427831788
2.7153304401106852e-104
[0.00000000e+000 3.32558703e-105 0.00000000e+000]
[0.00000000e+000 1.10595291e-209 0.00000000e+000]
1.1059529098487527e-209
3.3255870306590275e-105
True 1.9102560973445706e-104 2.7153304401106852e-104 0.0 0.24494897427831785
1.9102560973445706e-104
[0.00000000e+000 2.33957636e-105 0.00000000e+000]
[0.00000000e+000 5.47361754e-210 0.00000000e+000]
5.473617536163164e-210
2.339576358267275e-105
True 1.3438800315196121e-104 1.9102560973445706e-104 0.0 0.24494897427831785
1.3438800315196121e-104
[0.00000000e+000 1.64591018e-105 0.00000000e+000]
[0.00000000e+000 2.70902031e-210 0.00000000e+000]
2.7090203086757294e-210
1.645910176369

True 8.686894926203184e-121 1.2347972743524672e-120 0.0 0.24494897427831783
8.686894926203184e-121
[0.000000e+000 1.063923e-121 0.000000e+000]
[0.00000000e+000 1.13193215e-242 0.00000000e+000]
1.1319321518834194e-242
1.0639230009184967e-121
True 6.111298188479342e-121 8.686894926203184e-121 0.0 0.2449489742783178
6.111298188479342e-121
[0.00000000e+000 7.48478111e-122 0.00000000e+000]
[0.00000000e+000 5.60219483e-243 0.00000000e+000]
5.602194832276632e-243
7.484781113884782e-122
True 4.299345838275808e-121 6.111298188479342e-121 0.0 0.24494897427831783
4.299345838275808e-121
[0.00000000e+000 5.26560177e-122 0.00000000e+000]
[0.0000000e+000 2.7726562e-243 0.0000000e+000]
2.772656195564925e-243
5.265601765767067e-122
True 3.024623257942995e-121 4.299345838275808e-121 0.0 0.24494897427831788
3.024623257942995e-121
[0.00000000e+000 3.70439182e-122 0.00000000e+000]
[0.00000000e+000 1.37225188e-243 0.00000000e+000]
1.372251877873454e-243
3.704391823057402e-122
True 2.1278460018369937e-121 3.

4.7890677408158643e-138
[0.00000000e+000 5.86538615e-139 0.00000000e+000]
[0.00000000e+000 3.44027547e-277 0.00000000e+000]
3.440275473918475e-277
5.8653861543111336e-139
True 3.369146427761027e-138 4.7890677408158643e-138 0.0 0.24494897427831783
3.369146427761027e-138
[0.00000000e+000 4.12634481e-139 0.00000000e+000]
[0.00000000e+000 1.70267215e-277 0.00000000e+000]
1.7026721477542335e-277
4.126344808367611e-139
True 2.3702207331402482e-138 3.369146427761027e-138 0.0 0.24494897427831783
2.3702207331402482e-138
[0.00000000e+000 2.90291569e-139 0.00000000e+000]
[0.00000000e+000 8.42691949e-278 0.00000000e+000]
8.426919485711843e-278
2.902915686979531e-139
True 1.6674687325897296e-138 2.3702207331402482e-138 0.0 0.2449489742783178
1.6674687325897296e-138
[0.00000000e+000 2.04222378e-139 0.00000000e+000]
[0.00000000e+000 4.17067796e-278 0.00000000e+000]
4.170677961246598e-278
2.042223778445104e-139
True 1.1730772308622269e-138 1.6674687325897296e-138 0.0 0.24494897427831785
1.173077230862

2.1778298897601905e-154
[0.00000000e+000 2.66728599e-155 0.00000000e+000]
[0.00000000e+000 7.11441454e-310 0.00000000e+000]
7.1144145430993e-310
2.667285988247099e-155
True 1.5321202769428226e-154 2.1778298897601905e-154 0.0 0.2449489742783182
1.5321202769428226e-154
[0.00000000e+000 1.87645645e-155 0.00000000e+000]
[0.00000000e+000 3.52108881e-310 0.00000000e+000]
3.521088814529e-310
1.87645645154078e-155
True 1.0778585389319972e-154 1.5321202769428226e-154 0.0 0.24494897427831822
1.0778585389319972e-154
[0.00000000e+000 1.32010172e-155 0.00000000e+000]
[0.00000000e+000 1.74266854e-310 0.00000000e+000]
1.7426685449229e-310
1.320101717642589e-155
True 7.582818708377274e-155 1.0778585389319972e-154 0.0 0.24494897427831894
7.582818708377274e-155
[0.00000000e+000 9.28701832e-156 0.00000000e+000]
[0.00000000e+000 8.62487093e-311 0.00000000e+000]
8.6248709346174e-311
9.28701832377725e-156
True 5.3345719764942174e-155 7.582818708377274e-155 0.0 0.24494897427831808
5.3345719764942174e-155
[0.

True 3.3936902818888944e-11 4.823955562571113e-11 9.732968009404806e-162 0.24494897427831783
3.3936902818888944e-11
[0.00000000e+00 4.15640477e-12 0.00000000e+00]
[0.00000000e+00 1.72757006e-23 0.00000000e+00]
1.7275700594080675e-23
4.156404767834898e-12
True 2.3874875255377817e-11 3.3936902818888944e-11 9.732968009404806e-162 0.24494897427831785
2.3874875255377817e-11
[0.0000000e+00 2.9240631e-12 0.0000000e+00]
[0.00000000e+00 8.55014503e-24 0.00000000e+00]
8.55014502689778e-24
2.9240631024137935e-12
True 1.6796160554244514e-11 2.3874875255377817e-11 9.732968009404806e-162 0.24494897427831783
1.6796160554244514e-11
[0.00000000e+00 2.05710115e-12 0.00000000e+00]
[0.00000000e+00 4.23166514e-24 0.00000000e+00]
4.23166514045939e-24
2.0571011497880677e-12
True 1.18162296701598e-11 1.6796160554244514e-11 9.732968009404806e-162 0.24494897427831783
1.18162296701598e-11
[0.00000000e+00 1.44718667e-12 0.00000000e+00]
[0.00000000e+00 2.09434925e-24 0.00000000e+00]
2.094349254269471e-24
1.4471866

3.819029346410245e-28
True 2.1936951364259783e-27 3.1182244038066135e-27 9.732968009404806e-162 0.2449489742783178
2.1936951364259783e-27
[0.00000000e+00 2.68671687e-28 0.00000000e+00]
[0.00000000e+00 7.21844753e-56 0.00000000e+00]
7.218447527368486e-56
2.686716867734389e-28
True 1.5432816014473864e-27 2.1936951364259783e-27 9.732968009404806e-162 0.24494897427831783
1.5432816014473864e-27
[0.00000000e+00 1.89012623e-28 0.00000000e+00]
[0.00000000e+00 3.57257715e-56 0.00000000e+00]
3.572577152049014e-56
1.8901262264856848e-28
True 1.0857106175867094e-27 1.5432816014473864e-27 9.732968009404806e-162 0.24494897427831783
1.0857106175867094e-27
[0.00000000e+00 1.32971851e-28 0.00000000e+00]
[0.00000000e+00 1.76815132e-56 0.00000000e+00]
1.7681513177107706e-56
1.329718510704717e-28
True 7.638058692820492e-28 1.0857106175867094e-27 9.732968009404806e-162 0.24494897427831785
7.638058692820492e-28
[0.00000000e+00 9.35467321e-29 0.00000000e+00]
[0.00000000e+00 8.75099109e-57 0.00000000e+00]
8.7

4.937272059149281e-44
[0.00000000e+00 6.04689863e-45 0.00000000e+00]
[0.00000000e+00 3.65649831e-89 0.00000000e+00]
3.656498307908428e-89
6.046898633108073e-45
True 3.473409319145129e-44 4.937272059149281e-44 9.732968009404806e-162 0.24494897427831783
3.473409319145129e-44
[0.00000000e+00 4.25404025e-45 0.00000000e+00]
[0.00000000e+00 1.80968584e-89 0.00000000e+00]
1.8096858447486342e-89
4.254040249866748e-45
True 2.443570488680549e-44 3.473409319145129e-44 9.732968009404806e-162 0.24494897427831783
2.443570488680549e-44
[0.00000000e+00 2.99275042e-45 0.00000000e+00]
[0.0000000e+00 8.9565551e-90 0.0000000e+00]
8.956555099725746e-90
2.9927504238953414e-45
True 1.7190708564748368e-44 2.443570488680549e-44 9.732968009404806e-162 0.24494897427831783
1.7190708564748368e-44
[0.00000000e+00 2.10542322e-45 0.00000000e+00]
[0.00000000e+00 4.43280691e-90 0.00000000e+00]
4.432806914371693e-90
2.1054232150263028e-45
True 1.209379726621615e-44 1.7190708564748368e-44 9.732968009404806e-162 0.2449489

True 5.499657677128339e-61 7.817479510550321e-61 9.732968009404806e-162 0.24494897427831783
5.499657677128339e-61
[0.00000000e+00 6.73567753e-62 0.00000000e+00]
[0.00000000e+000 4.53693518e-123 0.00000000e+000]
4.5369351848395014e-123
6.735677534472313e-62
True 3.8690519782977287e-61 5.499657677128339e-61 9.732968009404806e-162 0.24494897427831783
3.8690519782977287e-61
[0.00000000e+00 4.73860157e-62 0.00000000e+00]
[0.00000000e+000 2.24543448e-123 0.00000000e+000]
2.2454344816154348e-123
4.738601567567625e-62
True 2.7219081785806644e-61 3.8690519782977287e-61 9.732968009404806e-162 0.2449489742783178
2.7219081785806644e-61
[0.00000000e+00 3.33364308e-62 0.00000000e+00]
[0.00000000e+000 1.11131762e-123 0.00000000e+000]
1.1113176198936465e-123
3.3336430821154903e-62
True 1.9148835875510676e-61 2.7219081785806644e-61 9.732968009404806e-162 0.2449489742783178
1.9148835875510676e-61
[0.00000000e+00 2.34524385e-62 0.00000000e+00]
[0.00000000e+000 5.50016873e-124 0.00000000e+000]
5.500168730

6.126102471818879e-78
[0.00000000e+00 7.50291258e-79 0.00000000e+00]
[0.00000000e+000 5.62936972e-157 0.00000000e+000]
5.629369724283806e-157
7.502912583979508e-79
True 4.3097607668231473e-78 6.126102471818879e-78 9.732968009404806e-162 0.24494897427831785
4.3097607668231473e-78
[0.0000000e+00 5.2783574e-79 0.0000000e+00]
[0.00000000e+000 2.78610568e-157 0.00000000e+000]
2.7861056800872057e-157
5.278357396091331e-79
True 3.03195024123279e-78 4.3097607668231473e-78 9.732968009404806e-162 0.24494897427831785
3.03195024123279e-78
[0.00000000e+00 3.71336551e-79 0.00000000e+00]
[0.00000000e+000 1.37890834e-157 0.00000000e+000]
1.3789083397967352e-157
3.7133655082643497e-79
True 2.1330005916054134e-78 3.03195024123279e-78 9.732968009404806e-162 0.24494897427831788
2.1330005916054134e-78
[0.00000000e+00 2.61238154e-79 0.00000000e+00]
[0.00000000e+000 6.82453729e-158 0.00000000e+000]
6.824537285683564e-158
2.612381535243955e-79
True 1.5005825167959023e-78 2.1330005916054134e-78 9.7329680094048

3.3773079994583405e-95
[0.00000000e+00 4.13634065e-96 0.00000000e+00]
[0.0000000e+000 1.7109314e-191 0.0000000e+000]
1.7109313984807947e-191
4.13634065144639e-96
True 2.375962462348746e-95 3.3773079994583405e-95 9.732968009404806e-162 0.2449489742783178
2.375962462348746e-95
[0.00000000e+00 2.90994784e-96 0.00000000e+00]
[0.00000000e+000 8.46779643e-192 0.00000000e+000]
8.467796433735474e-192
2.909947840380558e-96
True 1.6715080837743272e-95 2.375962462348746e-95 9.732968009404806e-162 0.24494897427831783
1.6715080837743272e-95
[0.00000000e+00 2.04717095e-96 0.00000000e+00]
[0.00000000e+000 4.19090891e-192 0.00000000e+000]
4.190908911184385e-192
2.0471709530921898e-96
True 1.1759189458578347e-95 1.6715080837743272e-95 9.732968009404806e-162 0.2449489742783178
1.1759189458578347e-95
[0.0000000e+00 1.4402007e-96 0.0000000e+00]
[0.00000000e+000 2.07417805e-192 0.00000000e+000]
2.0741780508411013e-192
1.4402006981115865e-96
True 8.27268130289278e-96 1.1759189458578347e-95 9.732968009404806

3.7620041279330254e-112
[0.00000000e+000 4.60749526e-113 0.00000000e+000]
[0.00000000e+000 2.12290126e-225 0.00000000e+000]
2.1229012587877675e-225
4.6074952618399594e-113
True 2.6465991827228833e-112 3.7620041279330254e-112 9.732968009404806e-162 0.24494897427831785
2.6465991827228833e-112
[0.00000000e+000 3.24140878e-113 0.00000000e+000]
[0.00000000e+000 1.05067309e-225 0.00000000e+000]
1.0506730850984152e-225
3.2414087756690225e-113
True 1.8619031228543441e-112 2.6465991827228833e-112 9.732968009404806e-162 0.24494897427831783
1.8619031228543441e-112
[0.0000000e+000 2.2803563e-113 0.0000000e+000]
[0.00000000e+000 5.20002486e-226 0.00000000e+000]
5.200024858342136e-226
2.2803563007438412e-113
True 1.3098633376468265e-112 1.8619031228543441e-112 9.732968009404806e-162 0.24494897427831788
1.3098633376468265e-112
[0.00000000e+000 1.60424841e-113 0.00000000e+000]
[0.00000000e+000 2.57361294e-226 0.00000000e+000]
2.5736129449669262e-226
1.60424840500682e-113
True 9.214990523679925e-113 1.

True 4.1905195086900546e-129 5.956607178294642e-129 9.732968009404806e-162 0.24494897427831785
4.1905195086900546e-129
[0.00000000e+000 5.13231728e-130 0.00000000e+000]
[0.00000000e+000 2.63406806e-259 0.00000000e+000]
2.6340680629067904e-259
5.132317276734546e-130
True 2.948063088111753e-129 4.1905195086900546e-129 9.732968009404806e-162 0.24494897427831783
2.948063088111753e-129
[0.00000000e+000 3.61062515e-130 0.00000000e+000]
[0.0000000e+000 1.3036614e-259 0.0000000e+000]
1.3036613957230503e-259
3.610625147703719e-130
True 2.0739853265123713e-129 2.948063088111753e-129 9.732968009404806e-162 0.24494897427831785
2.0739853265123713e-129
[0.00000000e+000 2.54010289e-130 0.00000000e+000]
[0.0000000e+000 6.4521227e-260 0.0000000e+000]
6.452122701882942e-260
2.540102891987437e-130
True 1.4590648185021378e-129 2.0739853265123713e-129 9.732968009404806e-162 0.24494897427831777
1.4590648185021378e-129
[0.00000000e+000 1.78698215e-130 0.00000000e+000]
[0.00000000e+000 3.19330522e-260 0.00000

True 6.635101328280968e-146 9.431454052126682e-146 9.732968009404806e-162 0.24494897427831794
6.635101328280968e-146
[0.00000000e+000 8.12630632e-147 0.00000000e+000]
[0.00000000e+000 6.60368545e-293 0.00000000e+000]
6.603685445483381e-293
8.126306322975636e-147
True 4.667845423752962e-146 6.635101328280968e-146 9.732968009404806e-162 0.2449489742783178
4.667845423752962e-146
[0.00000000e+000 5.71691974e-147 0.00000000e+000]
[0.00000000e+000 3.26831714e-293 0.00000000e+000]
3.2683171350077205e-293
5.716919743190139e-147
True 3.2838655842647902e-146 4.667845423752962e-146 9.732968009404806e-162 0.2449489742783178
3.2838655842647902e-146
[0.00000000e+000 4.02189753e-147 0.00000000e+000]
[0.00000000e+000 1.61756598e-293 0.00000000e+000]
1.6175659763278092e-293
4.021897532667645e-147
True 2.3102249960215153e-146 3.2838655842647902e-146 9.732968009404806e-162 0.24494897427831783
2.3102249960215153e-146
[0.00000000e+000 2.82943622e-147 0.00000000e+000]
[0.0000000e+000 8.0057093e-294 0.000000

True 0.006000000197276944 0.008528690575576984 2.153778475338863e-161 0.24494897439709945
0.006000000197276944
[-2.16000018e-08  7.34846947e-04  0.00000000e+00]
[4.66560077e-16 5.40000035e-07 0.00000000e+00]
5.400000352506502e-07
0.0007348469468199825
True 0.004221046835514205 0.006000000197276944 2.153778475338863e-161 0.2449489743371056
0.004221046835514205
[-1.06903428e-08  5.16970546e-04  0.00000000e+00]
[1.14283430e-16 2.67258546e-07 0.00000000e+00]
2.672585457505765e-07
0.0005169705463085653
True 0.0029695393002071497 0.004221046835514205 2.153778475338863e-161 0.24494897430741325
0.0029695393002071497
[-5.29090016e-09  3.63692803e-04  0.00000000e+00]
[2.79936245e-17 1.32272455e-07 0.00000000e+00]
1.322724548165695e-07
0.0003636928028110668
True 0.0020890940088960867 0.0029695393002071497 2.153778475338863e-161 0.24494897429271784
0.0020890940088960867
[-2.61858801e-09  2.55860717e-04  0.00000000e+00]
[6.85700318e-18 6.54647067e-08 0.00000000e+00]
6.546470666627337e-08
0.00025586

1.8565102998581838e-17
[0.00000000e+00 2.27375147e-18 0.00000000e+00]
[0.00000000e+00 5.16994574e-36 0.00000000e+00]
5.169945740219282e-36
2.273751468436971e-18
True 1.3060694446980568e-17 1.8565102998581838e-17 2.153778475338863e-161 0.24494897427831788
1.3060694446980568e-17
[0.00000000e+00 1.59960185e-18 0.00000000e+00]
[0.00000000e+00 2.55872609e-36 0.00000000e+00]
2.5587260915608355e-36
1.5996018540752056e-18
True 9.188300191516285e-18 1.3060694446980568e-17 2.153778475338863e-161 0.24494897427831783
9.188300191516285e-18
[0.00000000e+00 1.12533235e-18 0.00000000e+00]
[0.00000000e+00 1.26637291e-36 0.00000000e+00]
1.2663729061412728e-36
1.1253323536365925e-18
True 6.464040694936854e-18 9.188300191516285e-18 2.153778475338863e-161 0.2449489742783178
6.464040694936854e-18
[0.00000000e+00 7.91680069e-19 0.00000000e+00]
[0.00000000e+00 6.26757332e-37 0.00000000e+00]
6.267573315869958e-37
7.916800689590434e-19
True 4.5475029368739444e-18 6.464040694936854e-18 2.153778475338863e-161 0.2

[0.00000000e+00 7.27419389e-35 0.00000000e+00]
[0.00000000e+00 5.29138967e-69 0.00000000e+00]
5.291389673767585e-69
7.274193889200084e-35
True 4.178382072700533e-34 5.939354439537228e-34 2.153778475338863e-161 0.24494897427831788
4.178382072700533e-34
[0.00000000e+00 5.11745201e-35 0.00000000e+00]
[0.00000000e+00 2.61883151e-69 0.00000000e+00]
2.6188315118197803e-69
5.117452014254536e-35
True 2.939524307430545e-34 4.178382072700533e-34 2.153778475338863e-161 0.24494897427831783
2.939524307430545e-34
[0.00000000e+00 3.60016732e-35 0.00000000e+00]
[0.00000000e+00 1.29612047e-69 0.00000000e+00]
1.2961204730962532e-69
3.600167319856472e-35
True 2.0679782278479818e-34 2.939524307430545e-34 2.153778475338863e-161 0.24494897427831785
2.0679782278479818e-34
[0.00000000e+00 2.53274573e-35 0.00000000e+00]
[0.00000000e+00 6.41480093e-70 0.00000000e+00]
6.414800926279916e-70
2.532745728706282e-35
True 1.454838777840018e-34 2.0679782278479818e-34 2.153778475338863e-161 0.24494897427831794
1.4548387

True 9.095428288913642e-49 1.2928681831227895e-48 2.153778475338863e-161 0.24494897427831785
9.095428288913642e-49
[0.00000000e+00 1.11395791e-49 0.00000000e+00]
[0.00000000e+00 1.24090224e-98 0.00000000e+00]
1.2409022363815581e-98
1.1139579149956959e-49
True 6.3987045886574814e-49 9.095428288913642e-49 2.153778475338863e-161 0.24494897427831785
6.3987045886574814e-49
[0.00000000e+00 7.83678063e-50 0.00000000e+00]
[0.00000000e+00 6.14151306e-99 0.00000000e+00]
6.1415130619359464e-99
7.836780628508078e-50
True 4.501538477612096e-49 6.3987045886574814e-49 2.153778475338863e-161 0.2449489742783178
4.501538477612096e-49
[0.00000000e+00 5.51323616e-50 0.00000000e+00]
[0.0000000e+00 3.0395773e-99 0.0000000e+00]
3.0395772998133337e-99
5.513236163827316e-50
True 3.166867353329997e-49 4.501538477612096e-49 2.153778475338863e-161 0.24494897427831785
3.166867353329997e-49
[0.00000000e+00 3.87860455e-50 0.00000000e+00]
[0.00000000e+00 1.50435733e-99 0.00000000e+00]
1.504357325038101e-99
3.87860454

True 2.0470758771892177e-65 2.9098126948920445e-65 2.153778475338863e-161 0.24494897427831788
2.0470758771892177e-65
[0.00000000e+00 2.50714568e-66 0.00000000e+00]
[0.00000000e+000 6.28577947e-132 0.00000000e+000]
6.285779470455005e-132
2.507145681936932e-66
True 1.4401338114738946e-65 2.0470758771892177e-65 2.153778475338863e-161 0.24494897427831783
1.4401338114738946e-65
[0.0000000e+00 1.7637965e-66 0.0000000e+00]
[0.00000000e+000 3.11097809e-132 0.00000000e+000]
3.110978092425489e-132
1.7637964997202736e-66
True 1.013145344567324e-65 1.4401338114738946e-65 2.153778475338863e-161 0.2449489742783179
1.013145344567324e-65
[0.00000000e+00 1.24084456e-66 0.00000000e+00]
[0.00000000e+000 1.53969523e-132 0.00000000e+000]
1.5396952338276622e-132
1.2408445647330943e-66
True 7.127556349558343e-66 1.013145344567324e-65 2.153778475338863e-161 0.24494897427831783
7.127556349558343e-66
[0.00000000e+00 8.72943808e-67 0.00000000e+00]
[0.00000000e+000 7.62030893e-133 0.00000000e+000]
7.6203089274194

2.7010485302326253e-81
True 1.5515138760563346e-80 2.205396889854799e-80 2.153778475338863e-161 0.24494897427831788
1.5515138760563346e-80
[0.00000000e+00 1.90020866e-81 0.00000000e+00]
[0.00000000e+000 3.61079296e-162 0.00000000e+000]
3.610792961393025e-162
1.900208662592881e-81
True 1.0915020868438055e-80 1.5515138760563346e-80 2.153778475338863e-161 0.24494897427831788
1.0915020868438055e-80
[0.00000000e+00 1.33681158e-81 0.00000000e+00]
[0.00000000e+000 1.78706521e-162 0.00000000e+000]
1.7870652083765735e-162
1.3368115829751676e-81
True 7.678802129779496e-81 1.0915020868438055e-80 2.153778475338863e-161 0.24494897427831783
7.678802129779496e-81
[0.00000000e+00 9.40457353e-82 0.00000000e+00]
[0.00000000e+000 8.84460032e-163 0.00000000e+000]
8.844600322245914e-163
9.404573526878246e-82
True 5.402097060465254e-81 7.678802129779496e-81 2.153778475338863e-161 0.2449489742783179
5.402097060465254e-81
[0.00000000e+00 6.61619067e-82 0.00000000e+00]
[0.0000000e+000 4.3773979e-163 0.0000000e

1.1759189458578347e-95
[0.0000000e+00 1.4402007e-96 0.0000000e+00]
[0.00000000e+000 2.07417805e-192 0.00000000e+000]
2.0741780508411013e-192
1.4402006981115865e-96
True 8.27268130289278e-96 1.1759189458578347e-95 2.153778475338863e-161 0.24494897427831783
8.27268130289278e-96
[0.0000000e+00 1.0131924e-96 0.0000000e+00]
[0.00000000e+000 1.02655884e-192 0.00000000e+000]
1.0265588390884768e-192
1.0131923998375021e-96
True 5.819895680761116e-96 8.27268130289278e-96 2.153778475338863e-161 0.2449489742783178
5.819895680761116e-96
[0.00000000e+00 7.12788739e-97 0.00000000e+00]
[0.00000000e+000 5.08067786e-193 0.00000000e+000]
5.080677860241283e-193
7.127887387046237e-97
True 4.0943419061843796e-96 5.819895680761116e-96 2.153778475338863e-161 0.24494897427831783
4.0943419061843796e-96
[0.00000000e+00 5.01452425e-97 0.00000000e+00]
[0.00000000e+000 2.51454535e-193 0.00000000e+000]
2.5145453467106305e-193
5.014524251322981e-97
True 2.8804013962231735e-96 4.0943419061843796e-96 2.153778475338863e

True 9.214990523679925e-113 1.3098633376468265e-112 2.153778475338863e-161 0.24494897427831783
9.214990523679925e-113
[0.00000000e+000 1.12860124e-113 0.00000000e+000]
[0.00000000e+000 1.27374076e-226 0.00000000e+000]
1.273740755272662e-226
1.128601238379908e-113
True 6.482817551338047e-113 9.214990523679925e-113 2.153778475338863e-161 0.24494897427831783
6.482817551338047e-113
[0.00000000e+000 7.93979755e-114 0.00000000e+000]
[0.00000000e+000 6.30403851e-227 0.00000000e+000]
6.304038510590492e-227
7.93979754816865e-114
True 4.5607126014876854e-113 6.482817551338047e-113 2.153778475338863e-161 0.24494897427831788
4.5607126014876854e-113
[0.00000000e+000 5.58570937e-114 0.00000000e+000]
[0.00000000e+000 3.12001492e-227 0.00000000e+000]
3.120014915005284e-227
5.5857093685630335e-114
True 3.208496810013641e-113 4.5607126014876854e-113 2.153778475338863e-161 0.24494897427831788
3.208496810013641e-113
[0.00000000e+000 3.92959001e-114 0.00000000e+000]
[0.00000000e+000 1.54416777e-227 0.00000

[0.00000000e+000 1.47403154e-129 0.00000000e+000]
[0.00000000e+000 2.17276899e-258 0.00000000e+000]
2.1727689928717486e-258
1.4740315440558755e-129
True 8.46700963995812e-129 1.2035417159012394e-128 2.153778475338863e-161 0.24494897427831785
8.46700963995812e-129
[0.00000000e+000 1.03699266e-129 0.00000000e+000]
[0.00000000e+000 1.07535378e-258 0.00000000e+000]
1.0753537836471558e-258
1.0369926632561852e-129
True 5.956607178294642e-129 8.46700963995812e-129 2.153778475338863e-161 0.24494897427831783
5.956607178294642e-129
[0.00000000e+000 7.29532409e-130 0.00000000e+000]
[0.00000000e+000 5.32217536e-259 0.00000000e+000]
5.322175361476687e-259
7.295324092510686e-130
True 4.1905195086900546e-129 5.956607178294642e-129 2.153778475338863e-161 0.24494897427831785
4.1905195086900546e-129
[0.00000000e+000 5.13231728e-130 0.00000000e+000]
[0.00000000e+000 2.63406806e-259 0.00000000e+000]
2.6340680629067904e-259
5.132317276734546e-130
True 2.948063088111753e-129 4.1905195086900546e-129 2.153778

1.3543843871626048e-145
True 7.779742372921598e-145 1.1058502213801605e-144 2.153778475338863e-161 0.24494897427831785
7.779742372921598e-145
[0.00000000e+000 9.52819957e-146 0.00000000e+000]
[0.00000000e+000 9.07865871e-291 0.00000000e+000]
9.078658708354765e-291
9.528199571983558e-146
True 5.473109307107981e-145 7.779742372921598e-145 2.153778475338863e-161 0.24494897427831785
5.473109307107981e-145
[0.00000000e+000 6.70316255e-146 0.00000000e+000]
[0.00000000e+000 4.49323882e-291 0.00000000e+000]
4.493238823132801e-291
6.703162554446073e-146
True 3.85037499336919e-145 5.473109307107981e-145 2.153778475338863e-161 0.24494897427831783
3.85037499336919e-145
[0.00000000e+000 4.71572703e-146 0.00000000e+000]
[0.00000000e+000 2.22380814e-291 0.00000000e+000]
2.2238081384344176e-291
4.715727026063338e-146
True 2.7087687743252107e-145 3.85037499336919e-145 2.153778475338863e-161 0.24494897427831785
2.7087687743252107e-145
[0.00000000e+000 3.31755066e-146 0.00000000e+000]
[0.00000000e+000 1.

2.0526445891090437e-160
[0.00000000e+000 2.51396593e-161 0.00000000e+000]
[0.0e+000 6.3e-322 0.0e+000]
6.3e-322
2.514764455524206e-161
True 1.443936796281646e-160 2.0526445891090437e-160 2.153778475338863e-161 0.24487119474748192
1.443936796281646e-160
[0.00000000e+000 1.76845419e-161 0.00000000e+000]
[0.0e+000 3.1e-322 0.0e+000]
3.1e-322
1.7642600626891302e-161
True 1.0164239566766791e-160 1.443936796281646e-160 2.153778475338863e-161 0.2455312842168111
1.0164239566766791e-160
[0.00000000e+000 1.24486003e-161 0.00000000e+000]
[0.00e+000 1.53e-322 0.00e+000]
1.53e-322
1.2375796952551638e-161
True 7.161114794473528e-161 1.0164239566766791e-160 2.153778475338863e-161 0.24638994011624757
7.161114794473528e-161
[0.00000000e+000 8.77053862e-162 0.00000000e+000]
[0.e+000 8.e-323 0.e+000]
8e-323
8.89103499794031e-162
True 5.020743425955238e-161 7.161114794473528e-161 2.153778475338863e-161 0.24162928599873243
5.020743425955238e-161
[0.00000000e+000 6.14912976e-162 0.00000000e+000]
[0.e+000 4.

7.57917156145657e-17
[0.0000000e+00 9.2825515e-18 0.0000000e+00]
[0.00000000e+00 8.61657623e-35 0.00000000e+00]
8.6165762336988e-35
9.282551499290914e-18
True 5.3320061802506836e-17 7.57917156145657e-17 3.3342601497874983e-161 0.24494897427831783
5.3320061802506836e-17
[0.00000000e+00 6.53034722e-18 0.00000000e+00]
[0.00000000e+00 4.26454349e-35 0.00000000e+00]
4.264543485934721e-35
6.53034722349028e-18
True 3.7511078454553066e-17 5.3320061802506836e-17 3.3342601497874983e-161 0.24494897427831785
3.7511078454553066e-17
[0.0000000e+00 4.5941501e-18 0.0000000e+00]
[0.00000000e+00 2.11062151e-35 0.00000000e+00]
2.1106215102354526e-35
4.59415009575814e-18
True 2.638933563196811e-17 3.7511078454553066e-17 3.3342601497874983e-161 0.24494897427831785
2.638933563196811e-17
[0.00000000e+00 3.23202035e-18 0.00000000e+00]
[0.00000000e+00 1.04459555e-35 0.00000000e+00]
1.0445955526449922e-35
3.2320203474684255e-18
True 1.8565102998581838e-17 2.638933563196811e-17 3.3342601497874983e-161 0.24494897

2.0891910363502654e-34
True 1.2000557732854905e-33 1.7058173380848448e-33 3.3342601497874983e-161 0.2449489742783179
1.2000557732854905e-33
[0.00000000e+00 1.46976215e-34 0.00000000e+00]
[0.00000000e+00 2.16020079e-68 0.00000000e+00]
2.1602007884937546e-68
1.4697621537152719e-34
True 8.442485762354272e-34 1.2000557732854905e-33 3.3342601497874983e-161 0.24494897427831783
8.442485762354272e-34
[0.00000000e+00 1.03398911e-34 0.00000000e+00]
[0.00000000e+00 1.06913349e-68 0.00000000e+00]
1.0691334877133184e-68
1.0339891139239902e-34
True 5.939354439537228e-34 8.442485762354272e-34 3.3342601497874983e-161 0.2449489742783179
5.939354439537228e-34
[0.00000000e+00 7.27419389e-35 0.00000000e+00]
[0.00000000e+00 5.29138967e-69 0.00000000e+00]
5.291389673767585e-69
7.274193889200084e-35
True 4.178382072700533e-34 5.939354439537228e-34 3.3342601497874983e-161 0.24494897427831788
4.178382072700533e-34
[0.00000000e+00 5.11745201e-35 0.00000000e+00]
[0.00000000e+00 2.61883151e-69 0.00000000e+00]
2.6

3.8392227531944903e-50
[0.00000000e+00 4.70206838e-51 0.00000000e+00]
[0.0000000e+000 2.2109447e-101 0.0000000e+000]
2.2109447022969422e-101
4.702068377104848e-51
True 2.700923086567259e-50 3.8392227531944903e-50 3.3342601497874983e-161 0.24494897427831783
2.700923086567259e-50
[0.0000000e+00 3.3079417e-51 0.0000000e+00]
[0.00000000e+000 1.09424783e-101 0.00000000e+000]
1.0942478279328008e-101
3.3079416982963905e-51
True 1.9001204119979993e-50 2.700923086567259e-50 3.3342601497874983e-161 0.24494897427831785
1.9001204119979993e-50
[0.00000000e+00 2.32716273e-51 0.00000000e+00]
[0.00000000e+000 5.41568637e-102 0.00000000e+000]
5.415686370137169e-102
2.3271627296210225e-51
True 1.336749497994836e-50 1.9001204119979993e-50 3.3342601497874983e-161 0.24494897427831783
1.336749497994836e-50
[0.00000000e+00 1.63717709e-51 0.00000000e+00]
[0.00000000e+000 2.68034883e-102 0.00000000e+000]
2.680348830584169e-102
1.6371770920044567e-51
True 9.4041367542097e-51 1.336749497994836e-50 3.334260149787

True 2.4816891294661896e-66 3.527592999440549e-66 3.3342601497874983e-161 0.24494897427831785
2.4816891294661896e-66
[0.00000000e+00 3.03943603e-67 0.00000000e+00]
[0.0000000e+000 9.2381714e-134 0.0000000e+000]
9.238171402965975e-134
3.039436033701972e-67
True 1.7458876169352282e-66 2.4816891294661896e-66 3.3342601497874983e-161 0.2449489742783179
1.7458876169352282e-66
[0.0000000e+00 2.1382669e-67 0.0000000e+00]
[0.00000000e+000 4.57218536e-134 0.00000000e+000]
4.572185356451654e-134
2.1382669048675037e-67
True 1.2282455263135315e-66 1.7458876169352282e-66 3.3342601497874983e-161 0.24494897427831783
1.2282455263135315e-66
[0.00000000e+00 1.50428741e-67 0.00000000e+00]
[0.00000000e+000 2.26288061e-134 0.00000000e+000]
2.2628806093638045e-134
1.5042874091621602e-67
True 8.640802868843374e-67 1.2282455263135315e-66 3.3342601497874983e-161 0.24494897427831788
8.640802868843374e-67
[0.0000000e+00 1.0582779e-67 0.0000000e+00]
[0.00000000e+000 1.11995211e-134 0.00000000e+000]
1.1199521132731

True 2.2802503951114593e-82 3.2412582362791537e-82 3.3342601497874983e-161 0.24494897427831788
2.2802503951114593e-82
[0.00000000e+00 2.79272498e-83 0.00000000e+00]
[0.0000000e+000 7.7993128e-166 0.0000000e+000]
7.799312796608949e-166
2.7927249769014043e-83
True 1.604173899570202e-82 2.2802503951114593e-82 3.3342601497874983e-161 0.2449489742783178
1.604173899570202e-82
[0.00000000e+00 1.96470376e-83 0.00000000e+00]
[0.00000000e+000 3.86006085e-166 0.00000000e+000]
3.8600608500934015e-166
1.9647037563188506e-83
True 1.1285488232253906e-82 1.604173899570202e-82 3.3342601497874983e-161 0.24494897427831788
1.1285488232253906e-82
[0.00000000e+00 1.38218438e-83 0.00000000e+00]
[0.00000000e+000 1.91043367e-166 0.00000000e+000]
1.910433669605121e-166
1.3821843833603102e-83
True 7.939428803477282e-83 1.1285488232253906e-82 3.3342601497874983e-161 0.2449489742783178
7.939428803477282e-83
[0.00000000e+00 9.72377471e-84 0.00000000e+00]
[0.00000000e+000 9.45517946e-167 0.00000000e+000]
9.455179458

True 8.553464864455489e-98 1.215830879805003e-97 3.3342601497874983e-161 0.24494897427831783
8.553464864455489e-98
[0.00000000e+00 1.04758122e-98 0.00000000e+00]
[0.00000000e+000 1.09742642e-196 0.00000000e+000]
1.0974264178121178e-196
1.0475812225370011e-98
True 6.01742910158758e-98 8.553464864455489e-98 3.3342601497874983e-161 0.24494897427831788
6.01742910158758e-98
[0.00000000e+00 7.36981543e-99 0.00000000e+00]
[0.00000000e+000 5.43141795e-197 0.00000000e+000]
5.431417948894966e-197
7.369815431131886e-99
True 4.233308205088207e-98 6.01742910158758e-98 3.3342601497874983e-161 0.24494897427831783
4.233308205088207e-98
[0.00000000e+00 5.18472251e-99 0.00000000e+00]
[0.00000000e+000 2.68813475e-197 0.00000000e+000]
2.68813475389007e-197
5.184722513201714e-99
True 2.978165269041402e-98 4.233308205088207e-98 3.3342601497874983e-161 0.24494897427831783
2.978165269041402e-98
[0.00000000e+00 3.64749264e-99 0.00000000e+00]
[0.00000000e+000 1.33042026e-197 0.00000000e+000]
1.3304202554586669e

1.5879595096337313e-113
[0.00000000e+000 1.94484527e-114 0.00000000e+000]
[0.00000000e+000 3.78242311e-228 0.00000000e+000]
3.7824231063543e-228
1.944845265401415e-114
True 1.1171418737126074e-113 1.5879595096337313e-113 3.3342601497874983e-161 0.24494897427831785
1.1171418737126074e-113
[0.00000000e+000 1.36821378e-114 0.00000000e+000]
[0.00000000e+000 1.87200895e-228 0.00000000e+000]
1.8720089490031724e-228
1.368213780446306e-114
True 7.859180025880965e-114 1.1171418737126074e-113 3.3342601497874983e-161 0.24494897427831785
7.859180025880965e-114
[0.00000000e+000 9.62549043e-115 0.00000000e+000]
[0.0000000e+000 9.2650066e-229 0.0000000e+000]
9.265006601880945e-229
9.625490430040926e-115
True 5.528994314207959e-114 7.859180025880965e-114 3.3342601497874983e-161 0.24494897427831785
5.528994314207959e-114
[0.00000000e+000 6.77160743e-115 0.00000000e+000]
[0.00000000e+000 4.58546672e-229 0.00000000e+000]
4.5854667189815885e-229
6.771607430279452e-115
True 3.889690530802831e-114 5.5289943

1.0264634553469094e-129
[0.00000000e+000 1.25715585e-130 0.00000000e+000]
[0.00000000e+000 1.58044084e-260 0.00000000e+000]
1.5804408377440744e-260
1.2571558526070164e-130
True 7.221250295407441e-130 1.0264634553469094e-129 3.3342601497874983e-161 0.24494897427831783
7.221250295407441e-130
[0.00000000e+000 8.84418926e-131 0.00000000e+000]
[0.00000000e+000 7.82196837e-261 0.00000000e+000]
7.821968374338305e-261
8.844189264335259e-131
True 5.080205783974875e-130 7.221250295407441e-130 3.3342601497874983e-161 0.24494897427831785
5.080205783974875e-130
[0.00000000e+000 6.22195598e-131 0.00000000e+000]
[0.00000000e+000 3.87127362e-261 0.00000000e+000]
3.871273621129765e-261
6.221955979537114e-131
True 3.5739643069767875e-130 5.080205783974875e-130 3.3342601497874983e-161 0.24494897427831783
3.5739643069767875e-130
[0.00000000e+000 4.37719446e-131 0.00000000e+000]
[0.00000000e+000 1.91598313e-261 0.00000000e+000]
1.9159831301316101e-261
4.377194455506415e-131
True 2.5143117052140345e-130 3.5

KeyboardInterrupt: 

Rho is stable and therefore creates and infinite loop because at ap and periastron the orbit is parabolic to first order, so h'=h rho^1/4 and rho=30 h delta/ |x1-x2| = 30 h delta / sqrt(A(4 h^2 - h^2))=10sqrt(3)delta/sqrt(A). Computing A from the stable value of rho, I obtain A=1/200 exactly. I should prove this, for e=0.5 and a=50.

In [ ]:
npstar1x

In [ ]:
import matplotlib.pyplot as plt
t = np.linspace(0, 2*math.pi, 100)
xax=-200+np.arange(0,400)
plt.ylim(-200,200)
plt.xlim(-200,200)
plt.title("Elliptical Orbit, Adaptive RK4, a="+str(rad0)+", e="+ str(ecc0)+", theta="+str(round(180*theta0/math.pi))+ " degrees")
plt.plot(ellipsefns.getxtheory(theta0,ecc0,rad0,t,1),ellipsefns.getytheory(theta0,ecc0,rad0,t,1),'b')
plt.plot(ellipsefns.getxtheory(theta0,ecc0,rad0,t,-1),ellipsefns.getytheory(theta0,ecc0,rad0,t,-1),'g')
plt.plot(npstar1x[:,0],npstar1x[:,1],'y')
plt.plot(npstar2x[:,0],npstar2x[:,1],'r')
plt.show()

Adaptive RK4 orbits run and superficially look correct. 

In [ ]:
def getfocus(a,ecc):
    c=a*ecc
    return c

In [ ]:
def getsemiminor(a,ecc):
    c=getfocus(a,ecc)
    b=np.sqrt(a**2-c**2)
    return b

In [ ]:
def getxtheory2(theta0,ecc0,rad0,t, sgn):
    focus=getfocus(rad0,ecc0)
    b=getsemiminor(rad0,ecc0)
    xdim=rad0
    ydim=b
    xtheory=sgn*focus*np.cos(theta0)+xdim*np.cos(t)*np.cos(theta0)-ydim*np.sin(t)*np.sin(theta0)
    return xtheory

In [ ]:
def getytheory2(theta0, ecc0, rad0, t, sgn):
    focus = getfocus(rad0,ecc0)
    b=getsemiminor(rad0,ecc0)
    xdim=rad0
    ydim=b
    ytheory=sgn*focus*np.sin(theta0)+ydim*np.cos(theta0)*np.sin(t)+xdim*np.sin(theta0)*np.cos(t)
    return ytheory



In [ ]:
import matplotlib.pyplot as plt
t = np.linspace(0, 2*math.pi, 100)
xax=np.arange(0,100*len(npstar2x[:,1]))
xax=xax-len(xax)/2

plt.ylim(-200,200)
plt.xlim(-200,200)
#plt.ylim(-1,1)
#plt.xlim(74.999,75)
plt.title("Elliptical Orbit, RK4, a="+str(rad0)+", e="+ str(ecc0)+", theta="+str(round(180*theta0/math.pi))+ " degrees")
plt.plot(ellipsefns.getxtheory(theta0,ecc0,rad0,t,1),ellipsefns.getytheory(theta0,ecc0,rad0,t,1),'b')
plt.plot(ellipsefns.getxtheory(theta0,ecc0,rad0,t,-1),ellipsefns.getytheory(theta0,ecc0,rad0,t,-1),'g')
plt.plot(npstar1x[:,0],npstar1x[:,1],'y')
plt.plot(npstar2x[:,0],npstar2x[:,1],'r')
plt.plot(xax, np.tan(theta0)*xax,'c')
plt.show()

With adaptive step size I get inspirals!

In [ ]:
import matplotlib.pyplot as plt
t = np.linspace(0, 2*math.pi, 100)
xax=np.arange(0,100*len(npstar2x[:,1]))
xax=xax-len(xax)/2

#plt.ylim(-200,200)
#plt.xlim(-200,200)
plt.ylim(-1,1)
plt.xlim(74.999,75)
plt.title("Elliptical Orbit, RK4, a="+str(rad0)+", e="+ str(ecc0)+", theta="+str(round(180*theta0/math.pi))+ " degrees")
#plt.plot(ellipsefns.getxtheory(theta0,ecc0,rad0,t,1),ellipsefns.getytheory(theta0,ecc0,rad0,t,1),'b')
#plt.plot(ellipsefns.getxtheory(theta0,ecc0,rad0,t,-1),ellipsefns.getytheory(theta0,ecc0,rad0,t,-1),'g')
plt.plot(npstar1x[:,0],npstar1x[:,1],'*y')
plt.plot(npstar2x[:,0],npstar2x[:,1],'*r')
plt.plot(xax, np.tan(theta0)*xax,'c')
plt.show()

In [ ]:
import matplotlib.pyplot as plt
t = np.linspace(0, 2*math.pi, 100)
xax=np.arange(0,100*len(npstar2x[:,1]))
xax=xax-len(xax)/2

#plt.ylim(-200,200)
#plt.xlim(-200,200)
plt.ylim(-10,10)
plt.xlim(-25,-20)
plt.title("Elliptical Orbit, RK4, a="+str(rad0)+", e="+ str(ecc0)+", theta="+str(round(180*theta0/math.pi))+ " degrees")
#plt.plot(ellipsefns.getxtheory(theta0,ecc0,rad0,t,1),ellipsefns.getytheory(theta0,ecc0,rad0,t,1),'b')
#plt.plot(ellipsefns.getxtheory(theta0,ecc0,rad0,t,-1),ellipsefns.getytheory(theta0,ecc0,rad0,t,-1),'g')
plt.plot(npstar1x[:,0],npstar1x[:,1],'*y')
plt.plot(npstar2x[:,0],npstar2x[:,1],'*r')
plt.plot(xax, np.tan(theta0)*xax,'c')
plt.show()

# Conservation of angular momentum

In [ ]:
import Lstability

In [ ]:
deltaL, Lavg=Lstability.Lstability(npstar1x,npstar2x,mass0)
deltaL, Lavg

In [ ]:
deltaL*Lavg

Orbit conserves angular momentum to a tolerance of deltaL. 

# Conservation of Energy

In [ ]:
import Estability

In [ ]:
deltaE, Eavg = Estability.Estability(npstar1x, npstar2x, mass0)
deltaE, Eavg

In [ ]:
deltaE*Eavg

Orbit conserves energy to a relative error of deltaE. 

# Symmetry of the two stars orbits with respect to eachother 

In [ ]:
import orbitSymmetricTol

In [ ]:
allcancelsx, allcancelsa=orbitSymmetricTol.howSymmetric(npstar1x,npstar2x,npstar1a,npstar2a)

In [ ]:
allcancelsx

Orbit is symmetric with respect to x and v up to a tolerance of allcancelsx

In [ ]:
allcancelsa

In [ ]:
npstar1x

Orbit is symmetric with respect to a to up to or better than a tolerance of allcancelsa

# Testing for precision in perihelion and aphelion recovery from knowledge of the initial angle

In [ ]:
import aeTest

In [ ]:
from matplotlib import pyplot as plt
plt.plot( np.abs(npstar1x[:,1]))

In [ ]:
def findPerapHelionThetaIsZero(npstar1x,ecc0,rad0,useperihelion):
    maxindex=len(npstar1x[:,1])
    apindex=np.argmin(np.abs(npstar1x[10:int(maxindex/2),1]))+1
    print(apindex)
    delta=math.floor(.2*apindex)
    print(delta)
    perindex=np.argmin(np.abs(npstar1x[delta:apindex-delta,1]))+delta
    print(perindex)
    print(apindex/perindex)
    if np.abs(apindex/perindex-2.)>0.05: 
        perindex=np.argmin(np.abs(npstar1x[apindex+delta:2*apindex+delta,1]))+delta+apindex
        print(perindex)
        apindex,perindex=perindex,apindex
        print(apindex,perindex)
        print(apindex/perindex)
    #apindex3=np.argmin(np.abs(npstar1x[100:apindex2-100,1]))+100
    #apindex4=np.argmin(np.abs(npstar1x[100:apindex3-100,1]))+100
    #perindex=np.argmin(np.abs(npstar1x[100:apindex2-100,1]))+100
    if useperihelion:
        apindex,perindex=perindex,apindex
    coordap=[npstar1x[apindex,0],npstar1x[apindex,1]]
    coordper=[npstar1x[perindex,0],npstar1x[perindex,1]]
    ra=np.sqrt(np.sum(np.array(coordap)**2))
    rp=np.sqrt(np.sum(np.array(coordper)**2))
    e=(ra-rp)/(ra+rp)
    a=1./2.*(ra+rp)
    deltae=np.abs(e-ecc0)/ecc0
    deltaa=np.abs(a-rad0)/rad0
    return apindex,perindex,coordap,coordper,ra,rp,e,a,deltae,deltaa

In [ ]:
if theta0==0:
    apindex,perindex,coordap,coordper,ra,rp,e,a,deltae,deltaa=findPerapHelionThetaIsZero(npstar1x,ecc0,rad0,useperihelion)

In [ ]:
if theta0!=0:
    perindex,apindex,coordper,coordap,rp,ra,e,a,deltae,deltaa=aeTest.findPerApHelion(npstar1x,theta0,ecc0,rad0)

Recovered perihelion radius given by r_per, recovered aphelion radius given by r_ap, a is semimajor axis computed from the orbit, e is eccentricty computed from the orbit, delta a is relative error on the semimajor axis, and delta e is eccenticity relative error. 

In [ ]:
apindex,perindex,coordap,coordper,ra,rp,e,a,deltae,deltaa

In [ ]:
plt.plot(nptimes[:perindex],npstar1x[:perindex,1])

# Testing for symmetry within a given star's orbit about the line created by the initial angle with the origin that should pass thorugh the center of the ellipse, both focuses, and perihelion and aphelion

In [ ]:
pivotindex=perindex
endindex = apindex
if useperihelion:
    pivotindex=apindex
    endindex=perindex

In [ ]:
tosum1=list(range(0,endindex+1))
tosum2=list(range(endindex+1,pivotindex+1))

In [ ]:
len(tosum1)

In [ ]:
len(tosum2)

In [ ]:
apindex,perindex

In [ ]:
revtosum2=tosum2.reverse()

In [ ]:
xsum=np.zeros(endindex+1)
ysum=np.zeros(endindex+1)
for index in np.arange(0,pivotindex):
    xsum[index]=npstar1x[index,0]+npstar1x[pivotindex+1-index,0]
    ysum[index]=npstar1x[index,1]+npstar1x[pivotindex+1-index,1]

In [ ]:
xsum=xsum/2

In [ ]:
ysum=ysum/2

In [ ]:
import matplotlib.pyplot as plt
b0=np.tan(theta0)
plt.plot(xsum,ysum,label="Sum of data")
plt.plot(xsum,b0*xsum, color="green", label="Line defining perhelion")
plt.xlabel("Symmetric X sum")
plt.ylabel("Symmetric Y sum")
plt.legend()
plt.title("Sum of data reflection about perhelion")
plt.show()

In [ ]:
plt.plot(xsum,ysum-np.tan(theta0)*xsum, color="green", label="Residual")
plt.xlabel("Symmetric X sum")
plt.ylabel("Ysum-tan(theta)*Xsum")
plt.title("Residuals of data reflected about perihelion")
plt.legend()
plt.show()

The residual improves substantially from .2 at perihelion with a timestep of dt=1 to .125 at perihelion with a timestep of dt=.3 to .02 at perihelion with a timestep of dt=.1. I think timestep makes all the difference between adjacent pairs of points in resolving perihelion. I think it is difficult to tell how symmetric the orbit is by this method when the limitation is in the resolution of the orbit with timestep. Interpolation would be necessary to get a good picture of orbital shape. 

In the interest of accomplishing further orbital evolutions, I think I'm going to let the precice numerical characterization of orbital shape question go (the predicted and actual orbits overlap quite nicely) and move on to evolving parabolic and hyperbolic orbits. 

# Fit t as a function of the eccentric anomoly (angle from the center of the elipse)

In [ ]:
def findEccentricAnomoly(coordap, coordper):
    Ecenter=np.array(coordap)+np.array(coordper)
    Ecenter/=2.
    return Ecenter


In [ ]:
ellipsecenter=findEccentricAnomoly(coordap,coordper)

In [ ]:
ellipsecenter

In [ ]:
def getEllipsecenter(ecc,rad,theta, useperihelion):
    #ind of use perihelion
    rp=rad*(1-ecc)
    ra=-rad*(1+ecc)
    rcent=(rp+ra)/2
    #print(rp,ra,rcent)
    rcentx=rcent*np.cos(theta)
    rcenty=rcent* np.sin(theta)
    return [rcentx,rcenty]

In [ ]:
(np.array(coordap)+np.array(coordper))/2

In [ ]:
getEllipsecenter(ecc0,rad0,theta0, True)

In [ ]:
np.arctan2(-1.,0)/math.pi*180

In [ ]:
def getEang(npstar2x,ecc,rad,theta, useperihelion):
    ellipsecenter=getEllipsecenter(ecc,rad,theta, useperihelion)
    #print(ellipsecenter)
    #print(npstar1x)
    #print(npstar1x[:,0])
    xfortan=npstar2x[:,0]-ellipsecenter[0]
    yfortan=npstar2x[:,1]-ellipsecenter[1]
    #print("xy",xfortan,yfortan)
    Eang=np.arctan2(yfortan,xfortan)
    Eangtheta=2*np.arctan2(np.sqrt(1-ecc)*np.sin(theta/2.),np.sqrt(1+ecc)*np.cos(theta/2.))
    Eang-=Eangtheta
    #if useperihelion:
    #    Eang-=math.pi
    print(len(Eang))
    for i in np.arange(len(Eang)):
        #if xfortan[i]<0:
        #    Eang[i]+=math.pi
        if Eang[i]<0:
            Eang[i]+=2*math.pi
    print(xfortan,yfortan,Eang/math.pi*180)
    print("Eang",Eang)
    return xfortan, yfortan,Eang

In [ ]:
np.arctan2(-6.69327422*10**-6, -0.02240526)

In [ ]:
def xofeccanom(rad,Eang,ecc):
    return rad*(np.cos(Eang)+ecc)

In [ ]:
def yofeccanom(rad, Eang, ecc):
    b=getsemiminor(rad,ecc)
    return b*np.sin(Eang) 

In [ ]:
def tofEccAnom(npstar2x, rad,ecc,theta,mass, useperihelion):
    xE0,yE0,Eang=getEang(npstar2x,ecc,rad,theta, useperihelion)
    b=getsemiminor(rad,ecc)
    #fitval=rad*b*(Eang-ecc*np.sin(Eang))
    sgn=-1
    if useperihelion:
        sgn*=-1
    # added a factor of 2 in front of fitval
    fitval=rad**(1.5)*mass**(-.5)*(Eang-sgn*ecc*np.sin(Eang))
    fitval*=2
    print(Eang, ecc,rad,mass,fitval)
    return fitval

In [ ]:
def residualtEang(pars,nptimes,npstar2x):
    residual=np.abs(nptimes-tofEccAnom(npstar2x,pars['rad'],pars['ecc'],pars['theta'],pars['mass'],pars['useperihelion']))
    #print(nptimes, residual)
    return residual

In [ ]:
endindex=apindex
if useperihelion:
    endindex=perindex

In [ ]:
endindex

In [ ]:
xE0,yE0,Eang0=getEang(npstar2x[0:endindex-1,:],ecc0,rad0,theta0, useperihelion)

In [ ]:
nptimesoneorbit=nptimes[0:endindex-1]

In [ ]:
plt.plot(Eang0, xE0)

In [ ]:
plt.plot(Eang0, yE0)

In [ ]:
plt.plot(xE0,yE0)

In [ ]:
plt.plot(nptimesoneorbit,xE0)

In [ ]:
plt.plot(nptimesoneorbit,yE0)

In [ ]:
plt.plot(nptimesoneorbit,yE0/xE0)

In [ ]:
np.arctan(0./1.)

In [ ]:
yE0[0]

In [ ]:
xE0[0]

In [ ]:
plt.plot(nptimesoneorbit,np.arctan2(yE0,xE0)*180/math.pi)

In [ ]:
Eangtest=tofEccAnom(npstar2x[0:endindex-1,:],rad0,ecc0,theta0,masses[0], useperihelion)

In [ ]:
np.max(Eangtest)

In [ ]:
nptimes[0]

In [ ]:
nptimesoneorbit=nptimes[0:endindex-1]

In [ ]:
tpredoneorbit=Eangtest[0:endindex-1]

In [ ]:
Eangoneorbit=Eang0[0:endindex-1]

In [ ]:
plt.plot(nptimesoneorbit,npstar2x[0:endindex-1,1])

In [ ]:
plt.plot(nptimesoneorbit,Eangoneorbit/math.pi*180)

In [ ]:
plt.plot(nptimesoneorbit,tpredoneorbit)

In [ ]:
plt.plot(nptimesoneorbit,tpredoneorbit, label='times')
plt.xlabel("T timesteps")
plt.ylabel("T computed from angle")
plt.title("Times using start parameters")
plt.show()
plt.plot(nptimesoneorbit,tpredoneorbit-nptimesoneorbit, label='residual')
plt.legend()
plt.show()


# THERE IS A SECOND HARMONIC IN THIS TIMING DATA!!! I have heard of orbital resonances. Is that what I am seeing?

In [ ]:
from matplotlib import pyplot as plt

Arctan function is giving tangent output. I'm done for today. I'm asking for help on this, either Steve or on a forum. Clearly something really weird is going on. This is a distinct problem from the retrograde motion I had before I fixed the center, which you can tell from the sharply spiked top as opposed to the curved top I had before. Now the center appears to be in the correct location but there is some problem related to tangent versus arctangent. 

In [ ]:
plt.scatter(nptimesoneorbit,tpredoneorbit)

Retrograde motion as seen from the center of mass. I'm not sure that makes sense. So there's a problem with the definition of the Eang. The problem might be with the ellipse center, which probably shouldn't be at x=-70, if it spans between +5 and -95. 

In [ ]:
from lmfit import Minimizer,Parameters
pfittEang = Parameters()
pfittEang.add(name='theta', value=theta0, min=theta0-math.pi, max=theta0+math.pi, vary=True)
pfittEang.add(name='rad', value=rad0, min=0, vary=True)
pfittEang.add(name='ecc', value=ecc0, min=0, max=1.0, vary=True)
pfittEang.add(name='mass', value=masses[0], vary=False)
pfittEang.add(name='useperihelion', value=True, vary=False)

minit = Minimizer(residualtEang, pfittEang, fcn_args=(nptimesoneorbit,npstar2x[:endindex-1,:]))

outt = minit.leastsq()

In [ ]:
outt

Eccentricity fit is still not great for eccentricity of 0.9 (0.99), but radius fit is pretty good. The chi square is enormous. Eccentricity of 0.5 looks somewhat better (ecc 0.51) but still has a large chisquared and generates a potentially helpful divide by zero warning in the fit. 

In [ ]:
tfinal=nptimesoneorbit[endindex-2]
tfinal

Updated Jupyter and python packages and angular momentum and energy conservation improved by many orders of magnitude, but the fit is about the same. deltaL and deltaE are now consistent with roundoff error. 

In [ ]:
from scipy.fft import fft

In [ ]:
from scipy.signal import blackman
wndow=blackman(len(nptimesoneorbit))

In [ ]:
ftresiduals=fft(nptimesoneorbit-tpredoneorbit)

In [ ]:
xf = np.linspace(0.0, 1.0/(2.0*dt), len(nptimesoneorbit)//2)

In [ ]:
plt.semilogy(xf[1:len(nptimesoneorbit)//2], 2.0/len(nptimesoneorbit) * np.abs(ftresiduals[1:len(nptimesoneorbit)//2]), '-b')

In [ ]:
ftr=fft(np.sqrt(npstar1x[:endindex-1,0]**2+npstar1x[:endindex-1,1]**2))

In [ ]:
plt.xlabel("frequency")
plt.ylabel("Fourier transform of t(E)")
plt.title("Fourier transform of time computed from eccentric anomaly")
plt.semilogy(xf[1:len(nptimesoneorbit)//2], 2.0/len(nptimesoneorbit) * np.abs(ftr[1:len(nptimesoneorbit)//2]), '-b')

This is the fourier transform of the triangle wave.

In [ ]:
plt.title("Fourier transform of residuals of times")
plt.xlabel("frequency")
plt.ylabel("FT(t(E))")
plt.semilogy(xf[1:50], 2.0/len(nptimesoneorbit) * np.abs(ftresiduals[1:50]), '-b')

In [ ]:
plt.xlabel("bin number")
plt.ylabel("FT(t(E))")
plt.title("Fourier transform of residuals of times")
plt.semilogy(np.arange(1,30), 2.0/len(nptimesoneorbit[:29]) * np.abs(ftresiduals[1:30]), '*b')

Peak at the second harmonic and the sixth harmonic. The second harmonic seems natural due to the symmetry of the orbit but the sixth harmonic is harder to explain. 

Implementing the Adaptive RK4 hasn't changed the fit, residuals, or harmonics, sadly. There is still a 2% error in the fit for an eccentricity of 0.5